apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
type: Opaque
data:
  POSTGRES_USER: YXBwX3VzZXI=        
  POSTGRES_PASSWORD: c2VjdXJlUGFzcw== 
  POSTGRES_DB: YXBwX2Ri              
